import React,{useMemo,useState} from 'react';
import {CREATOR_PLATFORMS,CREATOR_STAGES,COLLABORATOR_ROLES,COLLAB_STATUSES,getConventionCreatorSummary,getCreatorCalendarEntries,getCreatorItemsForDate,getCreatorReminderItems,getDailyCreatorFocus,getItemEditProgress,getItemPlatformProgress,getItemShootProgress,localDate,normalizeCreatorItem,normalizeCreatorRoot,getLinkedCollaborators} from './creator-derived.js';

const Card=({children,className=''})=><section className={'card creator-card '+className}>{children}</section>;
const idFor=prefix=>prefix+'-'+Date.now()+'-'+Math.random().toString(36).slice(2,7);
const prettyDate=date=>date?new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric'}).format(new Date(date+'T12:00:00')):'Date TBD';
const emptyItem=stage=>normalizeCreatorItem({id:null,title:'',stage,platform:'TikTok',platforms:['TikTok'],cosplayId:'',conventionId:'',location:'',shootDate:'',editDate:'',uploadDeadline:'',reminderAt:'',captionDraft:'',shootList:[],editChecklist:[],platformChecklist:[{platform:'TikTok',ready:false,posted:false}],collaboratorIds:[],brandCollabId:null,analytics:{},hashtags:[],archiveLinks:[],notes:'',link:''});
const emptyContact=()=>({id:null,name:'',role:'Photographer',handle:'',link:'',notes:''});
const emptyCollab=()=>({id:null,brand:'',contactId:'',status:'Pitch / Inquiry',deliverable:'',dueDate:'',compensation:'',linkedItemIds:[],notes:''});
const emptyHashtag=()=>({id:null,text:'',category:'',notes:''});
const emptyArchive=()=>({id:null,label:'',url:'',note:''});
const asMoney=value=>Number.isFinite(Number(value))?Number(value):0;

export default function CreatorHQ({data,setData,setScreen}){
 const root=useMemo(()=>normalizeCreatorRoot(data.creator),[data.creator]);
 const [view,setView]=useState('Pipeline');
 const [stage,setStage]=useState('Ideas');
 const [draft,setDraft]=useState(null);
 const [selectedDay,setSelectedDay]=useState(localDate());
 const [month,setMonth]=useState(localDate().slice(0,7));
 const [tool,setTool]=useState('Contacts');
 const [contactDraft,setContactDraft]=useState(null);
 const [collabDraft,setCollabDraft]=useState(null);
 const [hashtagDraft,setHashtagDraft]=useState(null);
 const [archiveDraft,setArchiveDraft]=useState(null);
 const [conventionId,setConventionId]=useState(data.conventions?.items?.[0]?.id||'');
 const today=localDate();
 const conventions=data.conventions?.items||[];
 const projects=data.cosplay?.projects||[];
 const saveRoot=next=>setData({...data,creator:normalizeCreatorRoot(next)});
 const saveItem=item=>{const previous=root.items.find(x=>String(x.id)===String(item.id));const items=root.items.some(x=>String(x.id)===String(item.id))?root.items.map(x=>String(x.id)===String(item.id)?item:x):[...root.items,item];const collabs=root.collabs.map(collab=>{const linked=(collab.linkedItemIds||[]).filter(id=>String(id)!==String(item.id));return String(collab.id)===String(item.brandCollabId)?{...collab,linkedItemIds:[...linked,item.id]}:String(previous?.brandCollabId)===String(collab.id)?{...collab,linkedItemIds:linked}:collab});saveRoot({...root,items,collabs})};
 const deleteItem=id=>{if(window.confirm('Delete this content item?'))saveRoot({...root,items:root.items.filter(x=>String(x.id)!==String(id))})};
 const saveContact=e=>{e.preventDefault();if(!contactDraft?.name?.trim())return;const item={...contactDraft,id:contactDraft.id||idFor('contact'),name:contactDraft.name.trim()};const collaborators=contactDraft.id?root.collaborators.map(x=>String(x.id)===String(item.id)?item:x):[...root.collaborators,item];const ids=new Set(collaborators.map(x=>String(x.id)));saveRoot({...root,collaborators,items:root.items.map(x=>({...x,collaboratorIds:(x.collaboratorIds||[]).filter(id=>ids.has(String(id)))}))});setContactDraft(null)};
 const deleteContact=id=>{if(window.confirm('Remove this work contact?'))saveRoot({...root,collaborators:root.collaborators.filter(x=>String(x.id)!==String(id)),items:root.items.map(x=>({...x,collaboratorIds:(x.collaboratorIds||[]).filter(value=>String(value)!==String(id))}))})};
 const saveCollab=e=>{e.preventDefault();if(!collabDraft?.brand?.trim())return;const item={...collabDraft,id:collabDraft.id||idFor('collab'),brand:collabDraft.brand.trim()};saveRoot({...root,collabs:collabDraft.id?root.collabs.map(x=>String(x.id)===String(item.id)?item:x):[...root.collabs,item]});setCollabDraft(null)};
 const deleteCollab=id=>{if(window.confirm('Remove this brand collaboration?'))saveRoot({...root,collabs:root.collabs.filter(x=>String(x.id)!==String(id)),items:root.items.map(x=>x.brandCollabId===id?{...x,brandCollabId:null}:x)})};
 const saveHashtag=e=>{e.preventDefault();if(!hashtagDraft?.text?.trim())return;const item={...hashtagDraft,id:hashtagDraft.id||idFor('hashtag'),text:hashtagDraft.text.trim()};saveRoot({...root,hashtagBank:hashtagDraft.id?root.hashtagBank.map(x=>String(x.id)===String(item.id)?item:x):[...root.hashtagBank,item]});setHashtagDraft(null)};
 const deleteHashtag=id=>{if(window.confirm('Remove this hashtag?'))saveRoot({...root,hashtagBank:root.hashtagBank.filter(x=>String(x.id)!==String(id))})};
 const saveArchive=e=>{e.preventDefault();if(!archiveDraft?.label?.trim()||!archiveDraft?.url?.trim())return;const item={...archiveDraft,id:archiveDraft.id||idFor('archive'),label:archiveDraft.label.trim()};saveRoot({...root,archiveLinks:archiveDraft.id?root.archiveLinks.map(x=>String(x.id)===String(item.id)?item:x):[...root.archiveLinks,item]});setArchiveDraft(null)};
 const deleteArchive=id=>{if(window.confirm('Remove this archive link?'))saveRoot({...root,archiveLinks:root.archiveLinks.filter(x=>String(x.id)!==String(id))})};
 const focus=getDailyCreatorFocus(root,today);
 return <div className="creator-screen">
  <header><div><small>More · Creative studio</small><h1>Creator HQ</h1><p>Capture the idea, make the thing, share the magic.</p></div><div className="sparkle">✦</div></header>
  <div className="segmented creator-view-tabs" role="tablist">{['Pipeline','Calendar','Tools','Convention'].map(name=><button key={name} className={view===name?'selected':''} onClick={()=>setView(name)}>{name}</button>)}</div>
  {focus.due.length>0&&<Card className="creator-focus"><b>Today’s creator focus</b><small>{focus.due.length} item{focus.due.length===1?'':'s'} need attention today.</small><div>{focus.due.slice(0,3).map(item=><span key={item.id}>{item.title}</span>)}</div></Card>}
  {view==='Pipeline'&&<Pipeline root={root} stage={stage} setStage={setStage} draft={draft} setDraft={setDraft} saveItem={saveItem} deleteItem={deleteItem} projects={projects} conventions={conventions} contacts={root.collaborators} collabs={root.collabs} hashtagBank={root.hashtagBank}/>}
  {view==='Calendar'&&<CalendarView root={root} month={month} setMonth={setMonth} selectedDay={selectedDay} setSelectedDay={setSelectedDay} projects={projects} conventions={conventions} setDraft={setDraft}/>}
  {view==='Tools'&&<ToolsView root={root} tool={tool} setTool={setTool} contactDraft={contactDraft} setContactDraft={setContactDraft} saveContact={saveContact} deleteContact={deleteContact} collabDraft={collabDraft} setCollabDraft={setCollabDraft} saveCollab={saveCollab} deleteCollab={deleteCollab} hashtagDraft={hashtagDraft} setHashtagDraft={setHashtagDraft} saveHashtag={saveHashtag} deleteHashtag={deleteHashtag} archiveDraft={archiveDraft} setArchiveDraft={setArchiveDraft} saveArchive={saveArchive} deleteArchive={deleteArchive} />}
  {view==='Convention'&&<ConventionCreatorView root={root} conventions={conventions} conventionId={conventionId} setConventionId={setConventionId} projects={projects} contacts={root.collaborators} setDraft={setDraft} setScreen={setScreen}/>}
  {draft&&<ItemForm draft={draft} setDraft={setDraft} onSave={item=>{saveItem(item);setDraft(null)}} projects={projects} conventions={conventions} contacts={root.collaborators} collabs={root.collabs} hashtagBank={root.hashtagBank}/>}
 </div>;
}

function Pipeline({root,stage,setStage,draft,setDraft,saveItem,deleteItem,projects,conventions,contacts,collabs,hashtagBank}){
 const items=root.items.filter(item=>item.stage===stage);
 return <><div className="creator-stage-chips">{CREATOR_STAGES.map(name=><button key={name} className={stage===name?'selected':''} onClick={()=>setStage(name)}>{name} <small>{root.items.filter(x=>x.stage===name).length}</small></button>)}</div><div className="creator-pipeline">{items.map(item=><ContentCard key={item.id} item={item} onEdit={()=>setDraft(item)} onDelete={()=>deleteItem(item.id)} projects={projects} conventions={conventions} contacts={contacts} collabs={collabs}/>)}</div>{!items.length&&<Card className="empty-derived"><b>No {stage.toLowerCase()} items yet ✨</b><p>Capture the next little spark when it arrives.</p></Card>}<button className="primary creator-add-button" onClick={()=>setDraft(emptyItem(stage))}>+ Add content</button></>;
}

function ContentCard({item,onEdit,onDelete,projects,conventions,contacts,collabs}){
 const normalized=normalizeCreatorItem(item);const shoot=getItemShootProgress(normalized),edit=getItemEditProgress(normalized),platform=getItemPlatformProgress(normalized);const cosplay=projects.find(x=>String(x.id)===String(item.cosplayId)),convention=conventions.find(x=>String(x.id)===String(item.conventionId)),linked=getLinkedCollaborators(item,contacts),collab=collabs.find(x=>String(x.id)===String(item.brandCollabId));const reminder=item.reminderAt?item.reminderAt.slice(0,10):'';const current=localDate();const horizon=new Date(current+'T12:00:00');horizon.setDate(horizon.getDate()+3);const soonEnd=localDate(horizon);const dates=[item.shootDate,item.editDate,item.uploadDeadline,reminder].filter(Boolean);const overdue=dates.some(date=>date<current);const dueSoon=dates.some(date=>date>current&&date<=soonEnd);const due=dates.some(date=>date===current);
 return <Card className={due?'creator-due':''}><div className="creator-item-head"><div><h2>{item.title}</h2><span className="creator-stage-badge">{item.stage}</span></div><div className="card-actions"><button className="edit-action" onClick={onEdit}>Edit</button><button className="delete-action" onClick={onDelete}>Delete</button></div></div><p className="creator-meta">{(item.platforms||[]).join(' · ')||item.platform||'Platform TBD'}{item.shootDate?' · Shoot '+prettyDate(item.shootDate):''}{item.uploadDeadline?' · Post '+prettyDate(item.uploadDeadline):''}</p><div className="creator-link-row">{cosplay&&<span>✿ {cosplay.name}</span>}{convention&&<span>✦ {convention.name}</span>}{linked.map(contact=><span key={contact.id}>◎ {contact.name}</span>)}{collab&&<span>◇ {collab.brand}</span>}</div>{item.reminderAt&&<small className={(due||overdue||dueSoon)?'creator-alert':''}>Reminder {prettyDate(reminder)}{due?' · due today':overdue?' · overdue':dueSoon?' · due soon':''}</small>}{(shoot.total||edit.total||platform.total)&&<div className="creator-progress-row">{shoot.total>0&&<span>Shoot {shoot.done}/{shoot.total}</span>}{edit.total>0&&<span>Edit {edit.done}/{edit.total}</span>}{platform.total>0&&<span>Posted {platform.done}/{platform.total}</span>}</div>}</Card>;
}

function CalendarView({root,month,setMonth,selectedDay, setSelectedDay,projects,conventions,setDraft}){
 const year=Number(month.slice(0,4)),monthNumber=Number(month.slice(5,7)),daysInMonth=new Date(year,monthNumber,0).getDate(),first=new Date(year,monthNumber-1,1).getDay(),entries=getCreatorCalendarEntries(root),days=Array.from({length:daysInMonth},(_,i)=>month+'-'+String(i+1).padStart(2,'0')),selectedEntries=entries.filter(entry=>entry.date===selectedDay);
 const moveMonth=amount=>{const d=new Date(year,monthNumber-1+amount,1);setMonth(d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0'));};
 return <><div className="calendar-heading"><button className="secondary" onClick={()=>moveMonth(-1)}>‹</button><h2>{new Intl.DateTimeFormat(undefined,{month:'long',year:'numeric'}).format(new Date(year,monthNumber-1,1))}</h2><button className="secondary" onClick={()=>moveMonth(1)}>›</button></div><div className="creator-calendar-grid">{['S','M','T','W','T','F','S'].map((label,index)=><span className="calendar-weekday" key={index}>{label}</span>)}{Array.from({length:first},(_,i)=><span className="calendar-blank" key={'blank'+i}/>) }{days.map(day=>{const dayEntries=entries.filter(entry=>entry.date===day);return <button key={day} className={'creator-calendar-day '+(day===selectedDay?'selected ':'')+(day===localDate()?'today':'')} onClick={()=>setSelectedDay(day)}><b>{Number(day.slice(-2))}</b>{dayEntries.length>0&&<i>{dayEntries.length}</i>}</button>})}</div><Card className="creator-agenda"><div className="section-title-row"><h2>{prettyDate(selectedDay)}</h2><small>{selectedEntries.length} marker{selectedEntries.length===1?'':'s'}</small></div>{selectedEntries.length?selectedEntries.map(entry=><div className="creator-agenda-row" key={entry.id}><div><b>{entry.label}</b><span>{entry.item.title}</span><small>{entry.item.stage}</small></div><button className="edit-action" onClick={()=>setDraft(entry.item)}>Edit</button></div>):<p className="muted">Nothing planned for this day yet.</p>}</Card></>;
}

function ToolsView({root,tool,setTool,contactDraft,setContactDraft,saveContact,deleteContact,collabDraft,setCollabDraft,saveCollab,deleteCollab,hashtagDraft,setHashtagDraft,saveHashtag,deleteHashtag,archiveDraft,setArchiveDraft,saveArchive,deleteArchive}){
 return <><div className="creator-tool-tabs">{['Contacts','Brand collabs','Hashtag bank','Archive links'].map(name=><button key={name} className={tool===name?'selected':''} onClick={()=>setTool(name)}>{name}</button>)}</div>{tool==='Contacts'&&<ToolsList title="Work contacts" empty="No production contacts yet." items={root.collaborators} onAdd={()=>setContactDraft(emptyContact())} onEdit={setContactDraft} onDelete={deleteContact} render={(item)=><><b>{item.name}</b><small>{item.role} · {item.handle||'Contact details not added'}</small></>}/>} {tool==='Brand collabs'&&<ToolsList title="Brand collaborations" empty="No collaborations yet." items={root.collabs} onAdd={()=>setCollabDraft(emptyCollab())} onEdit={setCollabDraft} onDelete={deleteCollab} render={(item)=><><b>{item.brand}</b><small>{item.status} · {item.deliverable||'Deliverable TBD'}{item.dueDate?' · due '+prettyDate(item.dueDate):''}</small></>}/>} {tool==='Hashtag bank'&&<ToolsList title="Hashtag bank" empty="No saved hashtags yet." items={root.hashtagBank} onAdd={()=>setHashtagDraft(emptyHashtag())} onEdit={setHashtagDraft} onDelete={deleteHashtag} render={(item)=><><b>{item.text||item.tag}</b><small>{item.category||'Uncategorized'}</small></>}/>} {tool==='Archive links'&&<ToolsList title="Archive links" empty="No archive links yet." items={root.archiveLinks} onAdd={()=>setArchiveDraft(emptyArchive())} onEdit={setArchiveDraft} onDelete={deleteArchive} render={(item)=><><b>{item.label}</b><small>{item.url}</small></>}/>} {contactDraft&&<ContactForm draft={contactDraft} setDraft={setContactDraft} onSave={saveContact}/>} {collabDraft&&<CollabForm draft={collabDraft} setDraft={setCollabDraft} onSave={saveCollab} contacts={root.collaborators}/>} {hashtagDraft&&<HashtagForm draft={hashtagDraft} setDraft={setHashtagDraft} onSave={saveHashtag}/>} {archiveDraft&&<ArchiveForm draft={archiveDraft} setDraft={setArchiveDraft} onSave={saveArchive}/>}</>;
}
function ToolsList({title,empty,items,onAdd,onEdit,onDelete,render}){return <><Card><div className="section-title-row"><h2>{title}</h2><button className="primary" onClick={onAdd}>+ Add</button></div>{items.map(item=><div className="creator-tool-row" key={item.id}><div>{render(item)}</div><div className="card-actions"><button className="edit-action" onClick={()=>onEdit(item)}>Edit</button><button className="delete-action" onClick={()=>onDelete(item.id)}>Delete</button></div></div>)}{!items.length&&<p className="muted">{empty}</p>}</Card></>}

function ItemForm({draft,setDraft,onSave,projects,conventions,contacts,collabs,hashtagBank}){
 const [listText,setListText]=useState('');const [editText,setEditText]=useState('');const [archiveLabel,setArchiveLabel]=useState('');const [archiveUrl,setArchiveUrl]=useState('');
 const addList=(field,setter)=>{if(!listText.trim())return;setter({...draft,[field]:[...(draft[field]||[]),{id:idFor(field),text:listText.trim(),done:false}]});setListText('')};
 const addEdit=()=>{if(!editText.trim())return;setDraft({...draft,editChecklist:[...(draft.editChecklist||[]),{id:idFor('edit'),text:editText.trim(),done:false}]});setEditText('')};
 const addArchive=()=>{if(!archiveLabel.trim()||!archiveUrl.trim())return;setDraft({...draft,archiveLinks:[...(draft.archiveLinks||[]),{id:idFor('item-archive'),label:archiveLabel.trim(),url:archiveUrl.trim()}]});setArchiveLabel('');setArchiveUrl('')};
 const togglePlatform=platform=>{const platforms=(draft.platforms||[]).includes(platform)?(draft.platforms||[]).filter(x=>x!==platform):[...(draft.platforms||[]),platform];const checklist=platforms.map(name=>draft.platformChecklist?.find(x=>x.platform===name)||{id:idFor('platform'),platform:name,ready:false,posted:false});setDraft({...draft,platforms,platform:platforms[0]||'',platformChecklist:checklist})};
 const updateList=(field,id,patch)=>setDraft({...draft,[field]:(draft[field]||[]).map(x=>x.id===id?{...x,...patch}:x)});
 const removeList=(field,id)=>setDraft({...draft,[field]:(draft[field]||[]).filter(x=>x.id!==id)});
 return <Card className="creator-editor"><div className="section-title-row"><h2>{draft.id?'Edit content':'Add content'}</h2><button className="secondary" onClick={()=>setDraft(null)}>Cancel</button></div><div className="creator-form-grid">
  <label>Title<input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label>
  <label>Stage<select value={draft.stage} onChange={e=>setDraft({...draft,stage:e.target.value})}>{CREATOR_STAGES.map(x=><option key={x}>{x}</option>)}</select></label>
  <label>Location<input value={draft.location||''} onChange={e=>setDraft({...draft,location:e.target.value})}/></label>
  <label>Link<input value={draft.link||''} onChange={e=>setDraft({...draft,link:e.target.value})}/></label>
  <label>Cosplay<select value={draft.cosplayId||''} onChange={e=>setDraft({...draft,cosplayId:e.target.value||null})}><option value="">None</option>{projects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
  <label>Convention<select value={draft.conventionId||''} onChange={e=>setDraft({...draft,conventionId:e.target.value||null})}><option value="">None</option>{conventions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
  <label>Platforms <span className="creator-platform-picker">{CREATOR_PLATFORMS.map(platform=><button type="button" key={platform} className={(draft.platforms||[]).includes(platform)?'selected':''} onClick={()=>togglePlatform(platform)}>{platform}</button>)}</span></label>
  <label>Shoot date<input type="date" value={draft.shootDate||''} onChange={e=>setDraft({...draft,shootDate:e.target.value})}/></label>
  <label>Edit date<input type="date" value={draft.editDate||''} onChange={e=>setDraft({...draft,editDate:e.target.value})}/></label>
  <label>Upload deadline<input type="date" value={draft.uploadDeadline||''} onChange={e=>setDraft({...draft,uploadDeadline:e.target.value})}/></label>
  <label>Reminder<input type="datetime-local" value={draft.reminderAt||''} onChange={e=>setDraft({...draft,reminderAt:e.target.value})}/></label>
  <label className="form-field-wide">Caption draft<textarea value={draft.captionDraft||''} onChange={e=>setDraft({...draft,captionDraft:e.target.value})}/></label>
  <label className="creator-check-row form-field-wide"><input type="checkbox" checked={Boolean(draft.reminderDismissed)} onChange={e=>setDraft({...draft,reminderDismissed:e.target.checked})}/> Reminder dismissed</label>
  <label className="form-field-wide">Notes<textarea value={draft.notes||''} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label>
  <label>Brand collaboration<select value={draft.brandCollabId||''} onChange={e=>setDraft({...draft,brandCollabId:e.target.value||null})}><option value="">None</option>{collabs.map(x=><option key={x.id} value={x.id}>{x.brand}</option>)}</select></label>
  <fieldset className="creator-fieldset form-field-wide"><legend>Work collaborators</legend>{contacts.map(contact=><label className="creator-check-row" key={contact.id}><input type="checkbox" checked={(draft.collaboratorIds||[]).map(String).includes(String(contact.id))} onChange={e=>setDraft({...draft,collaboratorIds:e.target.checked?[...(draft.collaboratorIds||[]),contact.id]:(draft.collaboratorIds||[]).filter(id=>String(id)!==String(contact.id))})}/>{contact.name} · {contact.role}</label>)}{!contacts.length&&<small>No work contacts yet. Add one in Tools.</small>}</fieldset>
  <ChecklistEditor title="Shoot list" field="shootList" items={draft.shootList||[]} value={listText} setValue={setListText} onAdd={()=>addList('shootList',setDraft)} onUpdate={updateList} onRemove={removeList}/>
  <ChecklistEditor title="Editing checklist" field="editChecklist" items={draft.editChecklist||[]} value={editText} setValue={setEditText} onAdd={addEdit} onUpdate={updateList} onRemove={removeList}/>
  <fieldset className="creator-fieldset form-field-wide"><legend>Platform checklist</legend>{(draft.platformChecklist||[]).map(entry=><label className="creator-platform-row" key={entry.id||entry.platform}><b>{entry.platform}</b><span><label><input type="checkbox" checked={Boolean(entry.ready)} onChange={e=>updateList('platformChecklist',entry.id,{ready:e.target.checked})}/> Ready</label><label><input type="checkbox" checked={Boolean(entry.posted)} onChange={e=>updateList('platformChecklist',entry.id,{posted:e.target.checked})}/> Posted</label></span></label>)}</fieldset>
  <fieldset className="creator-fieldset form-field-wide"><legend>Hashtags</legend><div className="creator-hashtag-picker">{hashtagBank.map(tag=><button type="button" key={tag.id} className={(draft.hashtags||[]).includes(tag.text)?'selected':''} onClick={()=>setDraft({...draft,hashtags:(draft.hashtags||[]).includes(tag.text)?draft.hashtags.filter(x=>x!==tag.text):[...(draft.hashtags||[]),tag.text]})}>{tag.text}</button>)}</div><input placeholder="#customtag" value={draft._customHashtag||''} onChange={e=>setDraft({...draft,_customHashtag:e.target.value})}/><button type="button" className="secondary" onClick={()=>{if(draft._customHashtag?.trim())setDraft({...draft,hashtags:[...(draft.hashtags||[]),draft._customHashtag.trim()],_customHashtag:''})}}>Add hashtag</button></fieldset>
  <fieldset className="creator-fieldset form-field-wide"><legend>Archive / reference links</legend>{(draft.archiveLinks||[]).map(link=><div className="creator-check-row" key={link.id}><span>{link.label||'Link'} · {link.url}</span><button type="button" className="delete-action" onClick={()=>setDraft({...draft,archiveLinks:(draft.archiveLinks||[]).filter(x=>x.id!==link.id)})}>Delete</button></div>)}<div className="creator-add-row"><input value={archiveLabel} onChange={e=>setArchiveLabel(e.target.value)} placeholder="Label"/><input type="url" value={archiveUrl} onChange={e=>setArchiveUrl(e.target.value)} placeholder="https://…"/><button type="button" className="secondary" onClick={addArchive}>Add</button></div></fieldset>
  <label>Analytics views<input type="number" min="0" value={draft.analytics?.views||''} onChange={e=>setDraft({...draft,analytics:{...draft.analytics,views:e.target.value}})}/></label>
  <label>Analytics likes<input type="number" min="0" value={draft.analytics?.likes||''} onChange={e=>setDraft({...draft,analytics:{...draft.analytics,likes:e.target.value}})}/></label>
  <label>Analytics comments<input type="number" min="0" value={draft.analytics?.comments||''} onChange={e=>setDraft({...draft,analytics:{...draft.analytics,comments:e.target.value}})}/></label>
  <label>Analytics shares/saves<input type="number" min="0" value={draft.analytics?.shares||draft.analytics?.saves||''} onChange={e=>setDraft({...draft,analytics:{...draft.analytics,shares:e.target.value}})}/></label>
  <label className="form-field-wide">Analytics notes<textarea value={draft.analytics?.notes||''} onChange={e=>setDraft({...draft,analytics:{...draft.analytics,notes:e.target.value}})}/></label>
  </div><div className="form-actions"><button className="primary" onClick={()=>onSave(normalizeCreatorItem(draft))}>Save content</button><button className="secondary" onClick={()=>setDraft(null)}>Cancel</button></div></Card>;
}
function ChecklistEditor({title,field,items,value,setValue,onAdd,onUpdate,onRemove}){return <fieldset className="creator-fieldset form-field-wide"><legend>{title}</legend>{items.map(item=><div className="creator-check-row" key={item.id}><input type="checkbox" checked={Boolean(item.done)} onChange={e=>onUpdate(field,item.id,{done:e.target.checked})}/><input value={item.text} onChange={e=>onUpdate(field,item.id,{text:e.target.value})}/><button type="button" className="delete-action" onClick={()=>onRemove(field,item.id)}>Delete</button></div>)}<div className="creator-add-row"><input value={value} onChange={e=>setValue(e.target.value)} placeholder="Add a step"/><button type="button" className="secondary" onClick={onAdd}>Add</button></div></fieldset>}

function ConventionCreatorView({root,conventions,conventionId,setConventionId,projects,contacts,setDraft,setScreen}){
 const convention=conventions.find(item=>String(item.id)===String(conventionId));const summary=getConventionCreatorSummary(root,convention);return <><Card className="creator-convention-picker"><label>Convention<select value={conventionId} onChange={e=>setConventionId(e.target.value)}><option value="">Choose a convention</option>{conventions.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></Card>{convention?<><Card className="creator-convention-hero"><h2>{convention.name}</h2><strong>{summary.done} / {summary.target}</strong><small>{summary.remaining} content mission item{summary.remaining===1?'':'s'} remaining · target/done come from Convention</small><div className="creator-stage-summary">{CREATOR_STAGES.map(stage=><span key={stage}>{stage}: {summary.counts[stage]}</span>)}</div></Card><Card>{summary.items.map(item=><ContentCard key={item.id} item={item} onEdit={()=>setDraft(item)} onDelete={()=>{}} projects={projects} conventions={conventions} contacts={contacts} collabs={root.collabs}/>)}</Card>{!summary.items.length&&<Card><p className="muted">No linked content yet.</p></Card>}<button className="secondary" onClick={()=>setScreen?.('conventions')}>Open Convention</button></>:<Card><b>Choose a convention to plan its content.</b></Card>}</>;
}
function ContactForm({draft,setDraft,onSave}){return <Card className="creator-editor"><h2>{draft.id?'Edit work contact':'Add work contact'}</h2><form className="creator-form-grid" onSubmit={onSave}><label>Name<input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Role<select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}>{COLLABORATOR_ROLES.map(x=><option key={x}>{x}</option>)}</select></label><label>Handle / contact<input value={draft.handle||''} onChange={e=>setDraft({...draft,handle:e.target.value})}/></label><label>Link<input value={draft.link||''} onChange={e=>setDraft({...draft,link:e.target.value})}/></label><label className="form-field-wide">Notes<textarea value={draft.notes||''} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><div className="form-actions"><button className="primary">Save</button><button type="button" className="secondary" onClick={()=>setDraft(null)}>Cancel</button></div></form></Card>}
function CollabForm({draft,setDraft,onSave,contacts}){return <Card className="creator-editor"><h2>{draft.id?'Edit brand collaboration':'Add brand collaboration'}</h2><form className="creator-form-grid" onSubmit={onSave}><label>Brand / title<input required value={draft.brand} onChange={e=>setDraft({...draft,brand:e.target.value})}/></label><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{COLLAB_STATUSES.map(x=><option key={x}>{x}</option>)}</select></label><label>Contact<select value={draft.contactId||''} onChange={e=>setDraft({...draft,contactId:e.target.value||null})}><option value="">None</option>{contacts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Due date<input type="date" value={draft.dueDate||''} onChange={e=>setDraft({...draft,dueDate:e.target.value})}/></label><label>Deliverable<input value={draft.deliverable||''} onChange={e=>setDraft({...draft,deliverable:e.target.value})}/></label><label>Compensation / context<input value={draft.compensation||''} onChange={e=>setDraft({...draft,compensation:e.target.value})}/></label><label className="form-field-wide">Notes<textarea value={draft.notes||''} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><div className="form-actions"><button className="primary">Save</button><button type="button" className="secondary" onClick={()=>setDraft(null)}>Cancel</button></div></form></Card>}
function HashtagForm({draft,setDraft,onSave}){return <Card className="creator-editor"><h2>{draft.id?'Edit hashtag':'Add hashtag'}</h2><form className="creator-form-grid" onSubmit={onSave}><label>Tag<input required value={draft.text} onChange={e=>setDraft({...draft,text:e.target.value})}/></label><label>Category<input value={draft.category||''} onChange={e=>setDraft({...draft,category:e.target.value})}/></label><label className="form-field-wide">Notes<textarea value={draft.notes||''} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><div className="form-actions"><button className="primary">Save</button><button type="button" className="secondary" onClick={()=>setDraft(null)}>Cancel</button></div></form></Card>}
function ArchiveForm({draft,setDraft,onSave}){return <Card className="creator-editor"><h2>{draft.id?'Edit archive link':'Add archive link'}</h2><form className="creator-form-grid" onSubmit={onSave}><label>Label<input required value={draft.label} onChange={e=>setDraft({...draft,label:e.target.value})}/></label><label>URL<input required type="url" value={draft.url} onChange={e=>setDraft({...draft,url:e.target.value})}/></label><label className="form-field-wide">Note<textarea value={draft.note||''} onChange={e=>setDraft({...draft,note:e.target.value})}/></label><div className="form-actions"><button className="primary">Save</button><button type="button" className="secondary" onClick={()=>setDraft(null)}>Cancel</button></div></form></Card>}
