import React,{useMemo} from 'react';
import {getPlannedNeeds,toMoneyNumber} from './money-derived.js';
import {getHomeTaskPreview,getIncompleteTaskCount,getTasksForDate,localDate,shiftDate,taskTimeLabel} from './plan-derived.js';
import {workWindowApplies} from './yuu-context.js';
import CosplayThumbnail from './CosplayThumbnail.jsx';
import {getNextCosplayPiece,getPrimaryReference,getProjectProgress,getRemainingPieces,getTargetDateLabel} from './cosplay-derived.js';

const Card=({children,className=''})=><section className={'card '+className}>{children}</section>;
const money=value=>String.fromCharCode(36)+toMoneyNumber(value).toFixed(2);
const dateText=date=>new Intl.DateTimeFormat(undefined,{weekday:'long',month:'long',day:'numeric'}).format(new Date(date+'T12:00:00'));

function HomeTaskRow({task,onToggle}){
 return <div className={'home-task-row '+(task.urgent?'urgent-task':'')}><input aria-label={'Complete '+task.title} type="checkbox" checked={Boolean(task.done||task.completed)} onChange={onToggle}/><span className="task-copy"><b>{task.title}</b><small>{taskTimeLabel(task)}</small></span>{task.urgent&&<span className="urgent">Urgent</span>}</div>;
}

export default function HomeCommand({data,setData,setScreen}){
 const today=localDate(),tasks=data.tasks||[],preview=getHomeTaskPreview(tasks,today,3),incompleteCount=getIncompleteTaskCount(tasks,today),planned=getPlannedNeeds(data),m=data.money||{},available=toMoneyNumber(m.availableToday),earnedToday=toMoneyNumber(m.earnedToday),weeklyEarned=toMoneyNumber(m.weeklyEarned),weeklyGoal=toMoneyNumber(m.weeklyGoal),weeklyRemaining=Math.max(0,weeklyGoal-weeklyEarned),displayName=data.settings?.displayName||'Nyxie',hour=new Date().getHours(),greeting=hour<12?'Good morning':hour<17?'Good afternoon':'Good evening',project=(data.cosplay?.projects||[]).find(item=>item.id===data.cosplay?.activeId)||null,nextPiece=getNextCosplayPiece(project),remainingPieces=getRemainingPieces(project).length,progress=getProjectProgress(project),creatorItems=data.creator?.items||[],stageCounts=['To Film','Editing','Ready'].map(stage=>[stage,creatorItems.filter(item=>item.stage===stage).length]),nextShoot=creatorItems.filter(item=>item.shootDate>=today).sort((a,b)=>a.shootDate.localeCompare(b.shootDate))[0],nextUpload=creatorItems.filter(item=>item.uploadDeadline>=today).sort((a,b)=>a.uploadDeadline.localeCompare(b.uploadDeadline))[0],conventions=data.conventions?.items||[],nearest=conventions.filter(item=>item.startDate&&item.startDate>=today&&String(item.status||'').trim().toLowerCase()!=='completed').sort((a,b)=>a.startDate.localeCompare(b.startDate))[0],trip=(data.travel?.trips||[]).find(item=>item.status==='Traveling')||(data.travel?.trips||[]).filter(item=>item.startDate&&item.startDate>=today).sort((a,b)=>a.startDate.localeCompare(b.startDate))[0],wellness=data.wellness?.[today],routines=data.routines||[],routineDone=routines.reduce((count,routine)=>count+(routine.completion?.[today]?Object.values(routine.completion[today]).filter(Boolean).length:0),0),routineTotal=routines.reduce((count,routine)=>count+(routine.steps||[]).length,0),days=useMemo(()=>Array.from({length:7},(_,index)=>shiftDate(today,index)),[today]),windows=data.money?.workWindows||[];
 const toggleTask=task=>{const nextDone=!Boolean(task.done||task.completed);setData({...data,tasks:tasks.map(item=>item.id===task.id?{...item,done:nextDone,completed:false}:item)})};
 const dayLabel=day=>new Intl.DateTimeFormat(undefined,{weekday:'short',month:'numeric',day:'numeric'}).format(new Date(day+'T12:00:00'));
 const contentFor=day=>creatorItems.flatMap(item=>[{label:'Shoot · '+item.title,date:item.shootDate},{label:'Upload · '+item.title,date:item.uploadDeadline}].filter(entry=>entry.date===day));
 return <><header className="home-header"><div><small>{dateText(today)}</small><h1>{greeting}, {displayName} ✨</h1></div></header>
  <button type="button" className="yuu yuu-button" onClick={()=>setScreen('yuu')}><div className="yuu-avatar">Y</div><div><b>Yuu-Kun</b><p>Yare yare. {incompleteCount} things need you today.</p></div></button>
  <Section title="Today"/>
  <Card className="home-today-card"><div className="section-title-row"><b>{incompleteCount?incompleteCount+' tasks waiting':'Nothing urgent waiting'}</b><small>{dateText(today)}</small></div>{preview.length?preview.map(task=><HomeTaskRow key={task.id} task={task} onToggle={()=>toggleTask(task)}/>):<p className="plan-empty">Your list is clear today ✨</p>}{incompleteCount>preview.length&&<small className="more-tasks">+{incompleteCount-preview.length} more</small>}<button type="button" className="primary" onClick={()=>setScreen('plan')}>Open Plan</button></Card>
  <Section title="Money Today"/>
  <Card className="money-home"><div className="money-home-top"><div><small>Available Today</small><strong>{money(available)}</strong></div><div className="money-home-earned"><span>Earned today<br/><b>{money(earnedToday)}</b></span><span>Weekly Mission<br/><b>{money(weeklyEarned)} / {money(weeklyGoal)}</b></span></div></div><div className="money-home-bottom"><span>{money(weeklyRemaining)} left to goal</span>{planned.total>0&&<span>{money(planned.total)} planned needs</span>}</div><button type="button" className="primary" onClick={()=>setScreen('money')}>Open Money</button></Card>
  <Section title="Current Cosplay"/>
  <Card className="home-cosplay-card">{project?<><div className="home-cosplay-summary"><CosplayThumbnail reference={getPrimaryReference(project)} /><div><b>{project.name}</b><small>{progress}% ready · {remainingPieces} piece{remainingPieces===1?'':'s'} left</small><small>{project.targetEvent||'No target convention'}{project.targetDate?' · '+(getTargetDateLabel(project.targetDate)||project.targetDate):''}</small></div></div>{nextPiece&&<p className="next-piece"><b>Next:</b> {nextPiece.name}{nextPiece.due?' · due '+nextPiece.due:''}{nextPiece.urgent?' · Urgent':''}</p>}<button type="button" className="secondary" onClick={()=>setScreen('cosplay')}>Open Cosplay</button></>:<><div className="cosplay-thumb cosplay-thumb-placeholder">✿</div><b>No active cosplay yet ✨</b><small>Choose a project to track readiness here.</small><button type="button" className="secondary" onClick={()=>setScreen('cosplay')}>Open Cosplay</button></>}</Card>
  <Section title="Coming Up"/><Card><b>{nearest?.name||'No upcoming conventions yet.'}</b>{nearest&&<small>{nearest.startDate} · {nearest.location||nearest.venue||''}</small>}</Card>
  <Card className="home-quick-add"><div className="section-title-row"><h2>Quick Add</h2><small>Jump to the canonical editor</small></div><div className="quick-add-actions"><button type="button" className="primary" onClick={()=>setScreen('plan')}>+ Add task</button><button type="button" className="secondary" onClick={()=>setScreen('money')}>Log money</button><button type="button" className="secondary" onClick={()=>setScreen('cosplay')}>Add cosplay piece</button></div></Card>
  <details className="home-weekly"><summary>Weekly Planner</summary><div className="week-strip">{days.map(day=><button type="button" className={'day-card '+(day===today?'selected':'')} onClick={()=>setScreen('plan')} key={day}><b>{dayLabel(day)}</b>{getTasksForDate(tasks,day).slice(0,4).map(task=><small className="week-chip task-chip" key={task.id}>{taskTimeLabel(task)} · {task.title}</small>)}{windows.filter(window=>workWindowApplies(window,day)).map((window,index)=><small className="week-chip work-chip" key={'w'+index}>✦ Work {(window.start||'')+'–'+(window.end||'')}</small>)}{contentFor(day).map((entry,index)=><small className="week-chip content-chip" key={'c'+index}>✧ {entry.label}</small>)}</button>)}</div></details>
  <Section title="Creator HQ"/><Card className="creator-feature"><b>Creative studio</b><div className="money-stats">{stageCounts.map(([stage,count])=><div key={stage}><small>{stage}</small><b>{count}</b></div>)}</div><small>{nextShoot?'Next shoot · '+nextShoot.shootDate:'No shoot planned'}{nextUpload?' · Upload '+nextUpload.uploadDeadline:''}</small><button type="button" className="primary" onClick={()=>setScreen('creator')}>Open Creator HQ</button></Card>
  <Section title="Your World"/><div className="placeholder-grid"><Portal title="Conventions" text={nearest?nearest.name+' · '+nearest.startDate:'No upcoming convention'} onClick={()=>setScreen('conventions')}/><Portal title="Travel" text={trip?trip.destination+' · '+trip.startDate:'No upcoming trip'} onClick={()=>setScreen('travel')}/><Portal title="Wellness" text={wellness?wellness.energy+' · '+wellness.water+' water':'No check-in today'} onClick={()=>setScreen('wellness')}/><Portal title="Routines" text={routineTotal?routineDone+'/'+routineTotal+' steps':'No routines'} onClick={()=>setScreen('routines')}/><Portal title="Yuu-Kun" text="Open your bratty guide" onClick={()=>setScreen('yuu')}/><Portal title="Settings" text={(data.settings?.displayName||'Nyxie')+' · Yuu '+(data.settings?.yuuEnabled===false?'off':'on')} onClick={()=>setScreen('settings')}/></div>
 </>;
}
function Section({title}){return <div className="section-head"><h2>{title}</h2></div>}
function Portal({title,text,onClick}){return <Card><button type="button" className="project-card-button" onClick={onClick}><b>{title}</b><small>{text}</small></button></Card>}
