import React,{useState} from 'react';
import ModePicker from './ModePicker.jsx';
import YuuSprite from './YuuSprite.jsx';
const localDate=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};
const Card=({children})=><section className="card">{children}</section>,Header=({title})=><div className="section-head"><h2>{title}</h2></div>;
const Form=({children,onSubmit})=><Card><form className="log-form" onSubmit={onSubmit}>{children}</form></Card>;
export function YuuKun({data,setData}){const s=data.settings||{},tasks=(data.tasks||[]).filter(x=>!x.done).length,low=Object.values(data.wellness||{}).slice(-1)[0]?.energy==='Low',money=data.money||{},cosplay=data.cosplay?.projects?.find(x=>x.id===data.cosplay?.activeId),con=data.conventions?.items?.find(x=>x.startDate&&x.startDate>=localDate()&&x.status!=='Completed'),travel=data.travel?.trips?.find(x=>x.startDate===localDate()||x.status==='Traveling'),routine=(data.routines||[]).find(x=>!x.skipped?.[localDate()]),message=low?'Yare yare. Keep it small today.':money.weeklyGoal&&money.weeklyEarned<money.weeklyGoal/2?'Yare yare. Money mission needs a little push.':cosplay&&cosplay.pieces?.some(x=>x.status!=='Ready'&&x.due&&x.due<=localDate())?'Yare yare. Cosplay deadlines are getting bratty.':con?'Yare yare. '+con.name+' is next. Prep time.':travel?'Yare yare. Travel is close. Check your departure details.':routine?'Yare yare. One routine step at a time.':tasks>3?'Yare yare. That is a lot on the board.':'Yare yare. You are doing fine.';return <><header><small>More · Assistant</small><h1>Yuu-Kun</h1></header><Card><div className="yuu"><YuuSprite state={low?'sleepy':(money.weeklyGoal&&money.weeklyEarned<money.weeklyGoal/2)?'money':(cosplay||con)?'cosplay':'normal'} size="sm" /><div><b>Yuu-Kun</b><p>{s.yuuEnabled===false?'Prompts are off.':message}</p></div></div><p>He only helps with tasks, money, cosplay, conventions, travel, routines, and wellness.</p><button className="secondary" onClick={()=>setData({...data,settings:{...s,yuuEnabled:s.yuuEnabled===false}})}>{s.yuuEnabled===false?'Enable prompts':'Disable prompts'}</button></Card></>}
export function Settings({data,setData,cloud}){const s=data.settings||{yuuEnabled:true,nagLevel:'Normal',displayName:'Nyxie'},[name,setName]=useState(s.displayName),[email,setEmail]=useState(''),status=cloud?.status||'Local only',signedIn=Boolean(cloud?.session?.user);return <><header><small>More · Local preferences</small><h1>Settings</h1></header><ModePicker data={data} setData={setData}/><Card><h2>Cloud Sync</h2><strong className="cloud-sync-status">{status}</strong>{signedIn?<><p>Signed in as: <b>{cloud.email}</b></p>{cloud.notice&&<p className="muted">{cloud.notice}</p>}<button className="secondary" onClick={()=>cloud.signOut?.()}>Sign out</button></>:<><p className="muted">Your planner is still saved on this device.</p>{cloud.notice&&<p className="muted">{cloud.notice}</p>}<form className="log-form" onSubmit={e=>{e.preventDefault();cloud.sendMagicLink?.(email)}}><label>Email<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><button className="primary" type="submit" disabled={status==='Sending magic link…'}>{status==='Sending magic link…'?'Sending magic link…':'Send magic link'}</button></form></>}</Card><Card><label>Display name<input value={name} onChange={e=>setName(e.target.value)} onBlur={()=>setData({...data,settings:{...s,displayName:name}})}/></label><label>Yuu prompts<select value={s.yuuEnabled===false?'off':'on'} onChange={e=>setData({...data,settings:{...s,yuuEnabled:e.target.value==='on'}})}><option value="on">On</option><option value="off">Off</option></select></label><label>Nag level<select value={s.nagLevel||'Normal'} onChange={e=>setData({...data,settings:{...s,nagLevel:e.target.value}})}><option>Gentle</option><option>Normal</option><option>Bratty</option></select></label><button className="secondary" onClick={()=>{if(window.confirm('Reset local prototype data?')){localStorage.removeItem('nyxie-data');location.reload()}}}>Reset prototype data</button></Card></>}

