import React,{useMemo,useState} from 'react';
import {getDailyAffirmation,getMealCount,getWeekDates,getWeekKey,getWeeklyWellnessSummary,getWellnessDay,getWaterTotalOz,isLowEnergyDay,localDate,normalizeWellnessRoot,MEAL_TYPES,MOODS,ENERGIES,nonNegative} from './wellness-derived.js';

const Card=({children,className=''})=><section className={'card wellness-card '+className}>{children}</section>;
const Section=({title,children,action})=><Card><div className="section-title-row"><h2>{title}</h2>{action}</div>{children}</Card>;
const idFor=prefix=>prefix+'-'+Date.now()+'-'+Math.random().toString(36).slice(2,7);
const nowTime=()=>{const d=new Date();return String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')};
const prettyDate=date=>new Intl.DateTimeFormat(undefined,{weekday:'long',month:'short',day:'numeric'}).format(new Date(date+'T12:00:00'));
const inputNumber=value=>value===''?'':nonNegative(value);
const emptyMeal=()=>({id:null,type:'Breakfast',time:nowTime(),note:''});
const emptyGoal=()=>({id:null,title:'',type:'General',target:'',unit:'',active:true,note:''});
const emptyMedication=()=>({id:null,name:'',time:'',note:'',active:true});
const emptyMeasurement=()=>({id:null,date:localDate(),weight:'',label:'',value:'',unit:'',note:''});

export default function Wellness({data,setData,setScreen}){
 const [tab,setTab]=useState('Today');
 const [selectedDate,setSelectedDate]=useState(localDate());
 const [full,setFull]=useState(false);
 const [waterDraft,setWaterDraft]=useState(null);
 const [mealDraft,setMealDraft]=useState(null);
 const [goalDraft,setGoalDraft]=useState(null);
 const [medDraft,setMedDraft]=useState(null);
 const [measurementDraft,setMeasurementDraft]=useState(null);
 const root=useMemo(()=>normalizeWellnessRoot(data.wellness),[data.wellness]);
 const day=getWellnessDay(root,selectedDate);
 const low=isLowEnergyDay(root,selectedDate);
 const water=getWaterTotalOz(root,selectedDate);
 const meals=getMealCount(root,selectedDate);
 const saveRoot=next=>setData({...data,wellness:normalizeWellnessRoot(next)});
 const updateDay=patch=>saveRoot({...root,days:{...root.days,[selectedDate]:{...day,...patch}}});
 const updateSettings=patch=>saveRoot({...root,settings:{...root.settings,...patch}});
 const changeDate=amount=>setSelectedDate(date=>{const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+amount);return localDate(d)});

 const addWater=amount=>updateDay({waterEntries:[...(day.waterEntries||[]),{id:idFor('water'),amountOz:nonNegative(amount),time:nowTime()}]});
 const saveWater=e=>{e.preventDefault();if(!waterDraft)return;const entry={...waterDraft,id:waterDraft.id||idFor('water'),amountOz:nonNegative(waterDraft.amountOz),time:waterDraft.time||nowTime()};const entries=day.waterEntries||[];updateDay({waterEntries:waterDraft.id?entries.map(x=>x.id===waterDraft.id?entry:x):[...entries,entry]});setWaterDraft(null)};
 const deleteWater=id=>{if(window.confirm('Delete this water entry?'))updateDay({waterEntries:(day.waterEntries||[]).filter(x=>x.id!==id)})};
 const saveMeal=e=>{e.preventDefault();if(!mealDraft)return;const meal={...mealDraft,id:mealDraft.id||idFor('meal'),type:MEAL_TYPES.includes(mealDraft.type)?mealDraft.type:'Other'};const mealsList=day.meals||[];updateDay({meals:mealDraft.id?mealsList.map(x=>x.id===mealDraft.id?meal:x):[...mealsList,meal]});setMealDraft(null)};
 const deleteMeal=id=>{if(window.confirm('Delete this meal entry?'))updateDay({meals:(day.meals||[]).filter(x=>x.id!==id)})};
 const saveGoal=e=>{e.preventDefault();if(!goalDraft?.title?.trim())return;const goal={...goalDraft,id:goalDraft.id||idFor('goal'),title:goalDraft.title.trim()};saveRoot({...root,goals:goalDraft.id?root.goals.map(x=>x.id===goal.id?goal:x):[...root.goals,goal]});setGoalDraft(null)};
 const deleteGoal=id=>{if(window.confirm('Remove this goal?'))saveRoot({...root,goals:root.goals.filter(x=>x.id!==id)})};
 const saveMedication=e=>{e.preventDefault();if(!medDraft?.name?.trim())return;const item={...medDraft,id:medDraft.id||idFor('med'),name:medDraft.name.trim()};saveRoot({...root,medications:medDraft.id?root.medications.map(x=>x.id===item.id?item:x):[...root.medications,item]});setMedDraft(null)};
 const deleteMedication=id=>{if(window.confirm('Remove this item?'))saveRoot({...root,medications:root.medications.filter(x=>x.id!==id)})};
 const saveMeasurement=e=>{e.preventDefault();const item={...measurementDraft,id:measurementDraft.id||idFor('measurement')};saveRoot({...root,measurements:measurementDraft.id?root.measurements.map(x=>x.id===item.id?item:x):[...root.measurements,item]});setMeasurementDraft(null)};
 const deleteMeasurement=id=>{if(window.confirm('Delete this measurement?'))saveRoot({...root,measurements:root.measurements.filter(x=>x.id!==id)})};
 const toggleMedication=id=>updateDay({medicationLogs:{...(day.medicationLogs||{}),[id]:!day.medicationLogs?.[id]}});

 const week=getWeeklyWellnessSummary(root,selectedDate);
 const reflection=root.weeklyReflections?.[getWeekKey(selectedDate)]||{feltGood:'',feltHard:'',easier:''};
 const saveReflection=patch=>saveRoot({...root,weeklyReflections:{...root.weeklyReflections,[getWeekKey(selectedDate)]:{...reflection,...patch}}});
 const dayLabel=selectedDate===localDate()?'Today':prettyDate(selectedDate);
 const lowView=low&&!full;
 return <div className="wellness-screen">
  <header><div><small>More · Gentle care</small><h1>Wellness</h1><p>Optional check-ins for a softer day.</p></div><div className="sparkle">✦</div></header>
  <div className="wellness-date-nav"><button className="secondary" onClick={()=>changeDate(-1)} aria-label="Previous day">‹</button><strong>{dayLabel}</strong><button className="secondary" onClick={()=>changeDate(1)} aria-label="Next day">›</button></div>
  <div className="segmented wellness-tabs" role="tablist">{['Today','Log','Week','Goals'].map(label=><button key={label} role="tab" aria-selected={tab===label} className={tab===label?'selected':''} onClick={()=>setTab(label)}>{label}</button>)}</div>
  {tab==='Today'&&<>{lowView?<LowEnergyView day={day} water={water} goal={root.settings.waterGoalOz} meals={meals} onWater={addWater} onFull={()=>setFull(true)} />:<TodayView day={day} date={selectedDate} water={water} goal={root.settings.waterGoalOz} meals={meals} updateDay={updateDay} updateSettings={updateSettings} onWater={addWater} onEditWater={setWaterDraft} onDeleteWater={deleteWater} onMeal={setMealDraft} onEditMeal={setMealDraft} onDeleteMeal={deleteMeal} root={root} saveRoot={saveRoot} toggleMedication={toggleMedication} setScreen={setScreen} />}</>}
  {tab==='Log'&&<LogView day={day} water={water} goal={root.settings.waterGoalOz} meals={meals} onWater={addWater} onEditWater={setWaterDraft} onDeleteWater={deleteWater} onMeal={setMealDraft} onEditMeal={setMealDraft} onDeleteMeal={deleteMeal} updateDay={updateDay}/>}
  {tab==='Week'&&<WeekView summary={week} reflection={reflection} onReflection={saveReflection} />}
  {tab==='Goals'&&<GoalsView root={root} goalDraft={goalDraft} setGoalDraft={setGoalDraft} saveGoal={saveGoal} deleteGoal={deleteGoal} medDraft={medDraft} setMedDraft={setMedDraft} saveMedication={saveMedication} deleteMedication={deleteMedication} measurementDraft={measurementDraft} setMeasurementDraft={setMeasurementDraft} saveMeasurement={saveMeasurement} deleteMeasurement={deleteMeasurement} updateSettings={updateSettings} day={day} toggleMedication={toggleMedication} setScreen={setScreen} />}
  {waterDraft&&<WaterForm draft={waterDraft} setDraft={setWaterDraft} onSave={saveWater} />}
  {mealDraft&&<MealForm draft={mealDraft} setDraft={setMealDraft} onSave={saveMeal} />}
 </div>;
}

function TodayView({day,date,water,goal,meals,updateDay,updateSettings,onWater,onEditWater,onDeleteWater,onMeal,onEditMeal,onDeleteMeal,root,saveRoot,toggleMedication,setScreen}){
 const low=String(day.energy||'').toLowerCase()==='low';
 return <div className="wellness-sections">
  <Section title="How are we doing?"><div className="wellness-chip-group"><label>Mood<select value={day.mood||''} onChange={e=>updateDay({mood:e.target.value})}><option value="">Choose one</option>{MOODS.map(x=><option key={x}>{x}</option>)}</select></label><label>Energy<select value={day.energy||'Okay'} onChange={e=>updateDay({energy:e.target.value})}>{ENERGIES.map(x=><option key={x}>{x}</option>)}</select></label></div><div className="wellness-form-grid"><label>Sleep hours<input type="number" min="0" step=".5" value={day.sleep||''} onChange={e=>updateDay({sleep:inputNumber(e.target.value)})}/></label><label className="wellness-check-label"><input type="checkbox" checked={Boolean(day.rest)} onChange={e=>updateDay({rest:e.target.checked})}/> Rest day</label></div><label>Short note<textarea value={day.note||''} onChange={e=>updateDay({note:e.target.value})} placeholder="A few words, if useful"/></label>{low&&<p className="wellness-gentle-copy">Today can be smaller.</p>}</Section>
  <WaterSection day={day} water={water} goal={goal} onWater={onWater} onEdit={onEditWater} onDelete={onDeleteWater} updateSettings={updateSettings}/>
  <MealSection day={day} meals={meals} onAdd={onMeal} onEdit={onEditMeal} onDelete={onDeleteMeal}/>
  <Section title="Movement + rest"><div className="wellness-check-list"><label><input type="checkbox" checked={Boolean(day.movement)} onChange={e=>updateDay({movement:e.target.checked})}/> Movement done</label><label><input type="checkbox" checked={Boolean(day.gym)} onChange={e=>updateDay({gym:e.target.checked})}/> Gym / workout done</label></div><div className="wellness-form-grid"><label>Minutes<input type="number" min="0" value={day.movementMinutes||''} onChange={e=>updateDay({movementMinutes:inputNumber(e.target.value)})}/></label><label>Steps<input type="number" min="0" value={day.steps||''} onChange={e=>updateDay({steps:inputNumber(e.target.value)})}/></label></div><label>Movement note<textarea value={day.movementNote||''} onChange={e=>updateDay({movementNote:e.target.value})} placeholder="Optional"/></label></Section>
  <Section title="Support"><p className="wellness-affirmation">✦ {getDailyAffirmation(root,date)}</p><p className="muted">Only track what feels supportive.</p><div className="wellness-actions"><button className="secondary" onClick={()=>setScreen?.('plan')}>Appointments will appear here when they’re linked from Plan</button></div></Section>
  <Section title="Clear today’s check-in"><p className="muted">This only removes the selected day. Earlier days stay safe.</p><button className="delete-action" onClick={()=>{if(window.confirm('Clear this day’s Wellness check-in?')){const next={...root.days};delete next[date];saveRoot({...root,days:next});}}}>Clear selected day</button></Section>
 </div>;
}
function LowEnergyView({day,water,goal,meals,onWater,onFull}){
 const care=['Drink some water','Eat something','Rest for a bit','Stretch or wash your face'];
 return <div className="wellness-low-energy"><Card className="wellness-low-card"><small>Gentle mode</small><h2>Today can be smaller.</h2><p>Pick one small bit of care. Nothing here is a pass/fail test.</p><div className="wellness-priority-list"><b>Water · {water} / {goal} oz</b><b>Food · {meals} meal{meals===1?'':'s'}</b><b>Rest · {day.rest?'Rest day marked':'Not marked'}</b><b>Tiny care · {care[Math.abs(new Date().getDate())%care.length]}</b></div><div className="wellness-quick-water"><button className="primary" onClick={()=>onWater(8)}>+8 oz</button><button className="secondary" onClick={()=>onWater(12)}>+12 oz</button></div><button className="ghost" onClick={onFull}>Show Full Wellness</button></Card></div>;
}
function WaterSection({day,water,goal,onWater,onEdit,onDelete,updateSettings}){
 const percent=goal?Math.min(100,Math.round(water/goal*100)):0;
 return <Section title="Water log" action={<span className="wellness-total">{water} / {goal} oz</span>}><div className="progress"><i style={{width:percent+'%'}}/></div><p className="muted">Here’s where today is.</p><div className="wellness-quick-water"><button className="primary" onClick={()=>onWater(8)}>+8 oz</button><button className="secondary" onClick={()=>onWater(12)}>+12 oz</button><button className="secondary" onClick={()=>onWater(16)}>+16 oz</button><button className="secondary" onClick={()=>onEdit({id:null,amountOz:'',time:nowTime()})}>Custom</button></div><label>Daily water goal<input type="number" min="0" value={goal} onChange={e=>updateSettings({waterGoalOz:nonNegative(e.target.value)||64})}/></label><div className="wellness-log-list">{(day.waterEntries||[]).map(entry=><div className="wellness-log-row" key={entry.id}><span>{entry.amountOz} oz · {entry.time||'time not set'}</span><span className="card-actions"><button className="edit-action" onClick={()=>onEdit(entry)}>Edit</button><button className="delete-action" onClick={()=>onDelete(entry.id)}>Delete</button></span></div>)}{day.legacyWaterOz>0&&<p className="muted">Legacy water: {day.legacyWaterOz} oz from saved cups.</p>}</div></Section>;
}
function MealSection({day,meals,onAdd,onEdit,onDelete}){
 return <Section title="Food log" action={<span className="wellness-total">{meals} meal{meals===1?'':'s'}</span>}><p className="muted">Simple meal notes, no scoring.</p><button className="primary" onClick={()=>onAdd(emptyMeal())}>+ Log meal</button><div className="wellness-log-list">{(day.meals||[]).map(item=><div className="wellness-log-row" key={item.id}><span><b>{item.type}</b>{item.time?' · '+item.time:''}{item.note?' · '+item.note:''}</span><span className="card-actions"><button className="edit-action" onClick={()=>onEdit(item)}>Edit</button><button className="delete-action" onClick={()=>onDelete(item.id)}>Delete</button></span></div>)}{day.legacyMealCount>0&&<p className="muted">{day.legacyMealCount} saved meal count{day.legacyMealCount===1?'':'s'} from an older check-in.</p>}</div></Section>;
}
function LogView({day,water,goal,meals,onWater,onEditWater,onDeleteWater,onMeal,onEditMeal,onDeleteMeal,updateDay}){
 return <><WaterSection day={day} water={water} goal={goal} onWater={onWater} onEdit={onEditWater} onDelete={onDeleteWater} updateSettings={()=>{}}/><MealSection day={day} meals={meals} onAdd={onMeal} onEdit={onEditMeal} onDelete={onDeleteMeal}/><Section title="Movement log"><div className="wellness-check-list"><label><input type="checkbox" checked={Boolean(day.movement)} onChange={e=>updateDay({movement:e.target.checked})}/> Movement done</label><label><input type="checkbox" checked={Boolean(day.gym)} onChange={e=>updateDay({gym:e.target.checked})}/> Gym / workout done</label></div></Section></>;
}
function WeekView({summary,reflection,onReflection}){
 return <><Card className="wellness-week-hero"><h2>Here’s what your week looked like.</h2><p>No judgment, just context.</p></Card><div className="wellness-week-grid"><Card><b>Water</b><strong>{summary.waterTotalOz} oz</strong><small>{summary.waterAverageOz?summary.waterAverageOz+' oz average':'No water entries yet'}</small></Card><Card><b>Meals</b><strong>{summary.meals}</strong><small>countable meals</small></Card><Card><b>Sleep</b><strong>{summary.averageSleep==null?'—':summary.averageSleep+'h'}</strong><small>from logged nights</small></Card><Card><b>Movement</b><strong>{summary.movementDays} days</strong><small>{summary.gymDays} gym days · {summary.restDays} rest</small></Card><Card><b>Steps</b><strong>{summary.stepsTotal}</strong><small>{summary.averageSteps==null?'No step entries':summary.averageSteps+' average when logged'}</small></Card><Card><b>Energy</b><strong>{summary.energy||'—'}</strong><small>{summary.mood||'No mood notes yet'}</small></Card></div><Section title="Weekly reflection"><label>What felt good?<textarea value={reflection.feltGood||''} onChange={e=>onReflection({feltGood:e.target.value})}/></label><label>What felt hard?<textarea value={reflection.feltHard||''} onChange={e=>onReflection({feltHard:e.target.value})}/></label><label>What would make next week easier?<textarea value={reflection.easier||''} onChange={e=>onReflection({easier:e.target.value})}/></label></Section></>;
}
function GoalsView({root,goalDraft,setGoalDraft,saveGoal,deleteGoal,medDraft,setMedDraft,saveMedication,deleteMedication,measurementDraft,setMeasurementDraft,saveMeasurement,deleteMeasurement,updateSettings,day,toggleMedication,setScreen}){
 return <><Section title="Wellness goals" action={<button className="primary" onClick={()=>setGoalDraft(emptyGoal())}>+ Add goal</button>}><p className="muted">Your goals are personal planning notes, not recommendations.</p>{root.goals.map(goal=><div className="wellness-goal-row" key={goal.id}><div><b>{goal.title}</b><small>{goal.type}{goal.target!==''?' · '+goal.target+' '+(goal.unit||''):''}{goal.active===false?' · Archived':''}</small></div><div className="card-actions"><button className="edit-action" onClick={()=>setGoalDraft(goal)}>Edit</button><button className="delete-action" onClick={()=>deleteGoal(goal.id)}>Delete</button></div></div>)}</Section><Section title="Optional sections"><label className="wellness-check-label"><input type="checkbox" checked={Boolean(root.settings.showWeight)} onChange={e=>updateSettings({showWeight:e.target.checked})}/> Show weight and measurements</label><label className="wellness-check-label"><input type="checkbox" checked={Boolean(root.settings.showMedication)} onChange={e=>updateSettings({showMedication:e.target.checked})}/> Show medications / vitamins</label></Section>{root.settings.showWeight&&<MeasurementsSection items={root.measurements} draft={measurementDraft} setDraft={setMeasurementDraft} save={saveMeasurement} remove={deleteMeasurement}/>} {root.settings.showMedication&&<MedicationSection items={root.medications} draft={medDraft} setDraft={setMedDraft} save={saveMedication} remove={deleteMedication} day={day} toggle={toggleMedication}/>}<Section title="Appointments"><p className="muted">Appointments will appear here when they’re linked from Plan.</p><button className="secondary" onClick={()=>setScreen?.('plan')}>Open Plan</button></Section>{goalDraft&&<GoalForm draft={goalDraft} setDraft={setGoalDraft} onSave={saveGoal}/>} {medDraft&&<MedicationForm draft={medDraft} setDraft={setMedDraft} onSave={saveMedication}/>} {measurementDraft&&<MeasurementForm draft={measurementDraft} setDraft={setMeasurementDraft} onSave={saveMeasurement}/>}</>;
}
function WaterForm({draft,setDraft,onSave}){return <Card className="wellness-editor"><h2>{draft.id?'Edit water entry':'Add water entry'}</h2><form className="log-form" onSubmit={onSave}><label>Amount in ounces<input required type="number" min="0" value={draft.amountOz} onChange={e=>setDraft({...draft,amountOz:e.target.value})}/></label><label>Time<input type="time" value={draft.time||''} onChange={e=>setDraft({...draft,time:e.target.value})}/></label><div className="form-actions"><button className="primary">Save</button><button type="button" className="secondary" onClick={()=>setDraft(null)}>Cancel</button></div></form></Card>}
function MealForm({draft,setDraft,onSave}){return <Card className="wellness-editor"><h2>{draft.id?'Edit meal':'Log meal'}</h2><form className="log-form" onSubmit={onSave}><label>Type<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}>{MEAL_TYPES.map(x=><option key={x}>{x}</option>)}</select></label><label>Time<input type="time" value={draft.time||''} onChange={e=>setDraft({...draft,time:e.target.value})}/></label><label>Note<textarea value={draft.note||''} onChange={e=>setDraft({...draft,note:e.target.value})}/></label><div className="form-actions"><button className="primary">Save</button><button type="button" className="secondary" onClick={()=>setDraft(null)}>Cancel</button></div></form></Card>}
function GoalForm({draft,setDraft,onSave}){return <Card className="wellness-editor"><h2>{draft.id?'Edit goal':'Add goal'}</h2><form className="log-form" onSubmit={onSave}><label>Title<input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Type<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}>{['General','Water','Movement','Gym','Weight','Custom'].map(x=><option key={x}>{x}</option>)}</select></label><div className="wellness-form-grid"><label>Target<input value={draft.target} onChange={e=>setDraft({...draft,target:e.target.value})}/></label><label>Unit<input value={draft.unit} onChange={e=>setDraft({...draft,unit:e.target.value})}/></label></div><label className="wellness-check-label"><input type="checkbox" checked={draft.active!==false} onChange={e=>setDraft({...draft,active:e.target.checked})}/> Active</label><label>Note<textarea value={draft.note||''} onChange={e=>setDraft({...draft,note:e.target.value})}/></label><div className="form-actions"><button className="primary">Save</button><button type="button" className="secondary" onClick={()=>setDraft(null)}>Cancel</button></div></form></Card>}
function MeasurementsSection({items,draft,setDraft,save,remove}){return <Section title="Measurements" action={<button className="secondary" onClick={()=>setDraft(emptyMeasurement())}>+ Add</button>}><p className="muted">Optional dated notes. No health calculations.</p>{items.map(item=><div className="wellness-log-row" key={item.id}><span>{item.date} · {item.weight?item.weight+' weight':''}{item.label?' · '+item.label+' '+item.value+' '+item.unit:''}</span><span className="card-actions"><button className="edit-action" onClick={()=>setDraft(item)}>Edit</button><button className="delete-action" onClick={()=>remove(item.id)}>Delete</button></span></div>)}</Section>}
function MeasurementForm({draft,setDraft,onSave}){return <Card className="wellness-editor"><h2>{draft.id?'Edit measurement':'Add measurement'}</h2><form className="log-form" onSubmit={onSave}><label>Date<input type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>Weight (optional)<input type="number" min="0" value={draft.weight} onChange={e=>setDraft({...draft,weight:e.target.value})}/></label><div className="wellness-form-grid"><label>Measurement label<input value={draft.label} onChange={e=>setDraft({...draft,label:e.target.value})}/></label><label>Value / unit<input value={draft.value} onChange={e=>setDraft({...draft,value:e.target.value})}/></label></div><label>Unit<input value={draft.unit} onChange={e=>setDraft({...draft,unit:e.target.value})}/></label><label>Note<textarea value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/></label><div className="form-actions"><button className="primary">Save</button><button type="button" className="secondary" onClick={()=>setDraft(null)}>Cancel</button></div></form></Card>}
function MedicationSection({items,draft,setDraft,save,remove,day,toggle}){return <Section title="Medications / vitamins" action={<button className="secondary" onClick={()=>setDraft(emptyMedication())}>+ Add</button>}><p className="muted">Self-tracking only. No dosage or medical advice.</p>{items.map(item=><div className="wellness-log-row" key={item.id}><label className="wellness-check-label"><input type="checkbox" checked={Boolean(day.medicationLogs?.[item.id])} onChange={()=>toggle(item.id)}/><span><b>{item.name}</b><small>{item.time||'Any time'}</small></span></label><span className="card-actions"><button className="edit-action" onClick={()=>setDraft(item)}>Edit</button><button className="delete-action" onClick={()=>remove(item.id)}>Delete</button></span></div>)}</Section>}
function MedicationForm({draft,setDraft,onSave}){return <Card className="wellness-editor"><h2>{draft.id?'Edit item':'Add medication or vitamin'}</h2><form className="log-form" onSubmit={onSave}><label>Name<input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Time (optional)<input type="time" value={draft.time||''} onChange={e=>setDraft({...draft,time:e.target.value})}/></label><label>Note<textarea value={draft.note||''} onChange={e=>setDraft({...draft,note:e.target.value})}/></label><label className="wellness-check-label"><input type="checkbox" checked={draft.active!==false} onChange={e=>setDraft({...draft,active:e.target.checked})}/> Active</label><div className="form-actions"><button className="primary">Save</button><button type="button" className="secondary" onClick={()=>setDraft(null)}>Cancel</button></div></form></Card>}
